// src/components/CustomCursor.jsx
import { useEffect, useRef } from 'react';

export default function CustomCursor() {
  const dotRef = useRef(null);
  const ringRef = useRef(null);
  const posRef = useRef({ x: -200, y: -200 });
  const ringPos = useRef({ x: -200, y: -200 });
  const rafRef = useRef(null);
  const visibleRef = useRef(false);

  useEffect(() => {
    const isTouchDevice = window.matchMedia('(hover: none)').matches;
    if (isTouchDevice) return;

    const dot = dotRef.current;
    const ring = ringRef.current;

    const show = () => {
      dot.style.opacity = '1';
      ring.style.opacity = '1';
    };

    const hide = () => {
      dot.style.opacity = '0';
      ring.style.opacity = '0';
    };

    const onMove = (e) => {
      if (!visibleRef.current) {
        visibleRef.current = true;
        show();
      }
      posRef.current = { x: e.clientX, y: e.clientY };
      dot.style.left = `${e.clientX}px`;
      dot.style.top = `${e.clientY}px`;
    };

    const onMouseDown = () => {
      dot.classList.add('clicking');
      ring.classList.add('clicking');
    };

    const onMouseUp = () => {
      dot.classList.remove('clicking');
      ring.classList.remove('clicking');
    };

    const animate = () => {
      ringPos.current.x += (posRef.current.x - ringPos.current.x) * 0.12;
      ringPos.current.y += (posRef.current.y - ringPos.current.y) * 0.12;
      ring.style.left = `${ringPos.current.x}px`;
      ring.style.top = `${ringPos.current.y}px`;
      rafRef.current = requestAnimationFrame(animate);
    };
    rafRef.current = requestAnimationFrame(animate);

    window.addEventListener('mousemove', onMove);
    document.addEventListener('mouseleave', hide);
    document.addEventListener('mouseenter', show);
    window.addEventListener('mousedown', onMouseDown);
    window.addEventListener('mouseup', onMouseUp);

    return () => {
      window.removeEventListener('mousemove', onMove);
      document.removeEventListener('mouseleave', hide);
      document.removeEventListener('mouseenter', show);
      window.removeEventListener('mousedown', onMouseDown);
      window.removeEventListener('mouseup', onMouseUp);
      cancelAnimationFrame(rafRef.current);
    };
  }, []);

  return (
    <>
      <div ref={dotRef} className="cursor-dot hidden md:block" />
      <div ref={ringRef} className="cursor-ring hidden md:block" />
    </>
  );
}

// src/app/components/custom-cursor/custom-cursor.component.ts
import {
  Component,
  ViewChild,
  ElementRef,
  OnInit,
  OnDestroy,
  NgZone,
  ChangeDetectionStrategy,
} from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-custom-cursor',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div #dotEl class="cursor-dot hidden md:block"></div>
    <div #ringEl class="cursor-ring hidden md:block"></div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CustomCursorComponent implements OnInit, OnDestroy {
  @ViewChild('dotEl') dotEl!: ElementRef<HTMLDivElement>;
  @ViewChild('ringEl') ringEl!: ElementRef<HTMLDivElement>;

  private posRef = { x: -200, y: -200 };
  private ringPos = { x: -200, y: -200 };
  private rafRef?: number;
  private visible = false;

  constructor(private ngZone: NgZone) {}

  ngOnInit() {
    const isTouchDevice = window.matchMedia('(hover: none)').matches;
    if (isTouchDevice) return;

    this.ngZone.runOutsideAngular(() => {
      this.setupMouseTracking();
    });
  }

  private setupMouseTracking() {
    const dot = this.dotEl.nativeElement;
    const ring = this.ringEl.nativeElement;

    const show = () => {
      dot.style.opacity = '1';
      ring.style.opacity = '1';
    };

    const hide = () => {
      dot.style.opacity = '0';
      ring.style.opacity = '0';
    };

    const onMove = (e: MouseEvent) => {
      if (!this.visible) {
        this.visible = true;
        show();
      }
      this.posRef = { x: e.clientX, y: e.clientY };
      dot.style.left = `${e.clientX}px`;
      dot.style.top = `${e.clientY}px`;
    };

    const onMouseDown = () => {
      dot.classList.add('clicking');
      ring.classList.add('clicking');
    };

    const onMouseUp = () => {
      dot.classList.remove('clicking');
      ring.classList.remove('clicking');
    };

    const animate = () => {
      ring.style.left = `${this.ringPos.x}px`;
      ring.style.top = `${this.ringPos.y}px`;
      this.ringPos.x += (this.posRef.x - this.ringPos.x) * 0.12;
      this.ringPos.y += (this.posRef.y - this.ringPos.y) * 0.12;
      this.rafRef = requestAnimationFrame(animate);
    };

    window.addEventListener('mousemove', onMove);
    document.addEventListener('mouseleave', hide);
    document.addEventListener('mouseenter', show);
    window.addEventListener('mousedown', onMouseDown);
    window.addEventListener('mouseup', onMouseUp);

    this.ngZone.runOutsideAngular(() => {
      this.rafRef = requestAnimationFrame(animate);
    });
  }

  ngOnDestroy() {
    if (this.rafRef) {
      cancelAnimationFrame(this.rafRef);
    }
  }
}
